import { describe, test, expect } from 'vitest'
import { needsEnrichment, firstSubstantivePrompt } from '../src/shared/session-titles'
import type { TranscriptMessage } from '../src/shared/session-types'

const user = (text: string): TranscriptMessage => ({ role: 'user', text })

// The real store's two serializations of one slash-command invocation, copied
// verbatim from `~/.claude/projects` (sampled 2026-07-28). The second is the
// common one — 59 of the 65 enrichable rows lead with it — and it is exactly
// the shape `parseTranscript`'s unwrapper does NOT recognise, so it arrives
// here as raw markup rather than as `/clear`.
const INVOKE_MESSAGE_FIRST =
  '<command-message>preset</command-message>\n<command-name>/preset</command-name>\n<command-args>pick-up</command-args>'
const INVOKE_NAME_FIRST =
  '<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>'
const CAVEAT =
  '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response.</local-command-caveat>'
const STDOUT = '<local-command-stdout>Set model to \u001b[1mOpus 5\u001b[22m</local-command-stdout>'
const SKILL_BODY =
  'Base directory for this skill: C:\\Users\\S.D\\.claude\\skills\\preset\n\n# /preset\n\nDispatcher for the personal prompt-preset library.'

describe('needsEnrichment', () => {
  test('a bare slash command qualifies', () => {
    expect(needsEnrichment('/clear')).toBe(true)
    expect(needsEnrichment('/preset pick-up')).toBe(true)
    expect(needsEnrichment('/model opus default')).toBe(true)
  })

  // The token bound is the whole guard for the 28 informative titles that also
  // begin with a command. Four tokens is prose, and prose is left alone.
  test('a command carrying real prose is left alone', () => {
    expect(needsEnrichment('/relay N=1 read and follow .claude/relay-leg.md')).toBe(false)
    expect(needsEnrichment('/preset pick-up -> rehydrate state')).toBe(false)
  })

  test('a title that does not start with a slash never qualifies', () => {
    expect(needsEnrichment('Fix the parser')).toBe(false)
    expect(needsEnrichment('')).toBe(false)
    // Both conditions are required: short is not enough.
    expect(needsEnrichment('ship it')).toBe(false)
  })

  test('surrounding whitespace does not change the verdict', () => {
    expect(needsEnrichment('  /clear  ')).toBe(true)
    expect(needsEnrichment('\n/preset pick-up\n')).toBe(true)
  })
})

describe('firstSubstantivePrompt', () => {
  test('returns the first real user prompt, trimmed verbatim', () => {
    expect(
      firstSubstantivePrompt([
        user(CAVEAT),
        user(INVOKE_NAME_FIRST),
        user('  wire the  sessions rail\nto the switch  '),
        user('a later prompt')
      ])
    ).toBe('wire the  sessions rail\nto the switch')
  })

  // Ends of the ticket's definition, each measured in the store. A message that
  // fails any of these is CLI plumbing, not something the owner typed.
  test('skips every shape of command plumbing', () => {
    expect(firstSubstantivePrompt([user(CAVEAT), user('real prompt')])).toBe('real prompt')
    expect(firstSubstantivePrompt([user(STDOUT), user('real prompt')])).toBe('real prompt')
    expect(firstSubstantivePrompt([user(INVOKE_NAME_FIRST), user('real prompt')])).toBe(
      'real prompt'
    )
    expect(firstSubstantivePrompt([user(INVOKE_MESSAGE_FIRST), user('real prompt')])).toBe(
      'real prompt'
    )
    // What the parser's unwrapper turns an invocation into.
    expect(firstSubstantivePrompt([user('/preset pick-up'), user('real prompt')])).toBe(
      'real prompt'
    )
  })

  // 12 of the 15 otherwise-derivable labels were this one injected block, and
  // they share a ~40-character identical prefix — so accepting it leaves the
  // rows exactly as mutually indistinguishable as the bare commands did, which
  // is the defect being fixed.
  test('skips the injected skill body', () => {
    expect(firstSubstantivePrompt([user(SKILL_BODY), user('real prompt')])).toBe('real prompt')
  })

  test('ignores anything that is not a user message', () => {
    expect(
      firstSubstantivePrompt([
        { role: 'assistant', text: 'I will do that' },
        { role: 'tool', toolUseId: 't1', name: 'Read', input: {}, result: null, isError: false },
        user('the actual prompt')
      ])
    ).toBe('the actual prompt')
  })

  test('a session with nothing substantive returns null', () => {
    expect(firstSubstantivePrompt([user(CAVEAT), user(INVOKE_NAME_FIRST), user(STDOUT)])).toBe(
      null
    )
    expect(firstSubstantivePrompt([user('   ')])).toBe(null)
    expect(firstSubstantivePrompt([])).toBe(null)
  })
})
